// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACOUY4U0wVmHDMALg5ImC2ZhwCvZ5P36s',
    appId: '1:505019270233:web:12ac5e55de32de394d5d48',
    messagingSenderId: '505019270233',
    projectId: 'abc-123-learn',
    authDomain: 'abc-123-learn.firebaseapp.com',
    storageBucket: 'abc-123-learn.appspot.com',
    measurementId: 'G-90Y9EHGRFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkGUwvE3JxSdm-18NMOXU4itWT9mrcJlk',
    appId: '1:505019270233:android:b5aa1f9d2ed0be644d5d48',
    messagingSenderId: '505019270233',
    projectId: 'abc-123-learn',
    storageBucket: 'abc-123-learn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAen8aU_pzln-5D37FeKJUHUDDMNF4P22k',
    appId: '1:505019270233:ios:c74402b2b2d565e34d5d48',
    messagingSenderId: '505019270233',
    projectId: 'abc-123-learn',
    storageBucket: 'abc-123-learn.appspot.com',
    iosClientId: '505019270233-b5rfruvbiuuqs28rcqm8tp16fvqneqtr.apps.googleusercontent.com',
    iosBundleId: 'com.kidslearning.app',
  );
}
